lk/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from lk import views
from lk import viewsXls

app_name = 'lk'

urlpatterns = patterns('',
    url(r'^testView/$', views.testView, name='testView'),
    url(r'^price/(?P<organization>\d+)/$', viewsXls.price, name='price'),
    url(r'^directions/$', views.directions, name='directions'),
    url(r'^companies/$', views.companies, name='companies'),
    url(r'^companies/(?P<organization>\d+)/$', views.company, name='company'),
    url(r'^cdr/(?P<customer>\d+)/$', views.cdr, name='cdr'),
    url(r'^dashboard/(?P<customer>\d+)/$', views.dashboard, name='dashboard'),
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^request/$', views.requestConnect, name='requestConnect'),
    url(r'^login/$', views.loginView, name='loginView'),
    url(r'^logout/$', views.logoutView, name='logoutView'),
)

telefonzentrale/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from tastypie.api import Api
from lk.api import *

v1_api = Api(api_name='v1')
v1_api.register(OrganizationsResource())

urlpatterns = [
    # Examples:
    # url(r'^$', 'telefonzentrale.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^lk/', include('lk.urls', namespace="lk", app_name="lk")),
    url(r'^api/', include(v1_api.urls)),
]

lk/models.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from django.db import models
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _


# class Menu(models.Model):


PT = (
		("advance", "Аванс"),
		("credit", "Кредит"),
	)

CT = (
		("ip", "IP"),
		("sipid", "SIP ID"),
	)

class RequestConnect(models.Model):
	paymentType = models.CharField(db_column='paymentType', max_length=255, choices=PT)
	phoneNumber = models.CharField(db_column='phoneNumber', max_length=255)
	emailPrimary = models.EmailField(db_column='emailPrimary')
	ips = models.TextField(db_column='ips') 
	connectionType = models.CharField(db_column='connectionType', max_length=255, choices=CT)
	details = models.TextField(db_column='details')
	fullName = models.CharField(db_column='fullName', max_length=255)
	reasonId = models.ForeignKey('dir.DirReason', db_column='reasonId')

	class Meta:
		verbose_name = 'Заявка'
		verbose_name_plural = 'Заявки'


	def __str__(self):
		return self.fullName


   

class RequestConnectForm(ModelForm):
    class Meta:
        model = RequestConnect
        fields = '__all__'
        labels = {
            'phoneNumber': _('Номер телефона'),
            'paymentType': _('Тип оплаты Ter'),
        }

    def __init__(self, *args, **kwargs):
        super(RequestConnectForm, self).__init__(*args, **kwargs)
        self.fields['phoneNumber'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Номер телефона'})
        self.fields['paymentType'].widget.attrs.update({'class' : 'form-control m-b'})
        

# 3 Основание действия подписанта Устав, доверенность (предусмотрено поле 

# 7 Выбор услуг Список услуг выбирается галочками. 

# 8 Выбор тарифного плана Предвыбор из списка тарифных планов 

# 9 Пропуск А-номера Да, нет, если да – какой номер/номера, 

# 12 Заказ оборудования Да, нет, если да – предвыбор типа 

# 13 Заказ Asterisk*

lk/views.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from django.shortcuts import render

from django.http import HttpResponse
from django.template import RequestContext, loader
from models import *

from django.http import *
from django.shortcuts import render_to_response,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse

from viewsXls import *


def testView(request):
	template = loader.get_template('base.html')
	context = RequestContext(request, {
		'test': 'test',
	})
	return HttpResponse(template.render(context))

def directions(request):

	from voip.models import VoipDirection, VoipDirectionCodes
	from dir.models import DirCountry
	from django.db import connections
	cursor = connections['default'].cursor()

	query = """
	SELECT `voip_direction`.`directionId`, `name`, `countryName`, `countryITU`, codeList, `validFrom`, `validTill` FROM `voip_direction` 
	INNER JOIN `dir_country` ON ( `voip_direction`.`countryId` = `dir_country`.`countryId` ) 
	INNER JOIN (SELECT *,GROUP_CONCAT(`prefix`) as codeList FROM `voip_directionCodes` GROUP BY directionId) as codes on codes.`directionId` = `voip_direction`.`directionId`
	WHERE `validFrom` < CURRENT_TIMESTAMP() AND (`validTill` IS NULL OR `validTill` > CURRENT_TIMESTAMP())
	ORDER BY `voip_direction`.`name` ASC
	"""

	# cursor.execute(query)


	# directions = VoipDirection.objects.select_related('countryId').all().order_by('countryId__countryName').order_by('name')

	# directionCodes = VoipDirectioncodes.objects.values('directionid').annotate(emails=GroupConcat('VoipDirectioncodes__prefix'))

	# result = cursor.fetchall()
	# print result

	result = VoipDirection.objects.raw(query)
	print result
	for p in result:
		print p.__dict__

	template = loader.get_template('directions.html')
	context = RequestContext(request, {
		'test': 'test',
		'directions': result,
		'page': 'directions',
	})
	return HttpResponse(template.render(context))

@login_required(login_url='/lk/login')
def dashboard(request, customer):

	from voip.models import VoipCdr
	from core.models import CoreCustomers

	template = loader.get_template('dashboard.html')
	context = RequestContext(request, {
		'test': 'test',
		'title': 'Панель управления',
		'page': 'dashboard',
	})
	return HttpResponse(template.render(context))

@login_required(login_url='/lk/login')
def clients(request):

	from core.models import CoreOrganizations

	organizations = CoreOrganizations.objects.all()

	template = loader.get_template('clients.html')
	context = RequestContext(request, {
		'test': 'test',
		'title': 'Клиенты',
		'page': 'clients',
		'organizations': organizations,
	})
	return HttpResponse(template.render(context))

@login_required(login_url='lk/login')
def cdr(request, customer):

	from voip.models import VoipCdr
	from core.models import CoreCustomers

	#TODO добавить 
	customerObj = CoreCustomers.objects.get(customerid=customer)
	print customerObj.shortname
	cdrsObj = VoipCdr.objects.filter(a=customerObj).order_by('-callDate')[:5]
	for i in cdrsObj:
		print i.recordId

	template = loader.get_template('cdr.html')
	context = RequestContext(request, {
		'test': 'test',
		'cdrs': cdrsObj,
		'page': 'cdr',
	})
	return HttpResponse(template.render(context))



@login_required(login_url='lk/login')
def companies(request):

	from core.models import CoreOrganizations

	companies = CoreOrganizations.objects.all()

	template = loader.get_template('companies.html')
	context = RequestContext(request, {
		'test': 'test',
		'companies': companies,
		'page': 'companies',
	})
	return HttpResponse(template.render(context))


@login_required(login_url='lk/login')
def company(request, organization):

	from core.models import CoreOrganizations

	company = CoreOrganizations.objects.select_related('bankAccountIdForInvoice', 'cityId', 'bankAccountIdForInvoice__bankId').get(organizationId=organization)
	tariffs = CoreOrganizations.objects.getTariffs(1)

	template = loader.get_template('company.html')
	context = RequestContext(request, {
		'test': 'test',
		'company': company,
		'tariffs': tariffs,
		'page': 'companies',
	})
	return HttpResponse(template.render(context))



def requestConnect(request):

	if request.method == 'POST': # If the form has been submitted...
		
		form = RequestConnectForm(request.POST) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			# Process the data in form.cleaned_data
			# ...
			return HttpResponseRedirect('/thanks/') # Redirect after POST
	else:
		form = RequestConnectForm() # An unbound form

	return render(request, 'request.html', {
		'form': form,
	})


def loginView(request):

	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('lk.views.dashboard', args=('1',)))

	error = ''

	if request.method == 'POST': # If the form has been submitted...
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('lk.views.dashboard', args=('1',)))
			else:
				error = "Ваш аккаунт не активен, обратитесь в техническую поддержку"
		else:
			error = "Неверный логин или пароль"
		

	template = loader.get_template('login.html')
	context = RequestContext(request, {
		'test': 'test',
		'error': error
	})
	return HttpResponse(template.render(context))


	# template = loader.get_template('request.html')
	# context = RequestContext(request, {
	# 	'test': 'test',
	# })
	# return HttpResponse(template.render(context))

def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('lk.views.loginView'))

lk/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Telefonzentrale | {{ Title }}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    {% block css %}

    {% endblock %}

</head>

<body>



    <div id="wrapper">

        {% include "nav.html" %}
        {% include "searchHide.html" %}
        {% include "bottomSideBar.html" %}


        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>{% block pageTitle %}{{ title }}{% endblock %}</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html">This is</a>
                        </li>
                        <li class="active">
                            <strong>Breadcrumb</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-sm-8">
                    <div class="title-action">
                        <a href="" class="btn btn-primary">This is action area</a>
                    </div>
                </div>
            </div>



                    {% block content %}

                    {% endblock %}



            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Heinzelmaennchen Ltd. &copy; 2012-2015
                </div>
            </div>

        </div>
        </div>

    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

    {% block scripts %}

    {% endblock %}


</body>

</html>

lk/templates/cdr.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/plugins/dataTables/dataTables.bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/dataTables/dataTables.responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/dataTables/dataTables.tableTools.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mediaPlayer/mediaelementplayer.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

            <div class="col-lg-12">
                <div class="wrapper wrapper-content">



<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>Детализация звонков</h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>



    <div class="ibox-content">

        <table class="table table-striped table-bordered table-hover dataTables-example" >
            <thead>
                <tr>
                    <th>Дата</th>
                    <th>А-номер</th>
                    <th>Б-номер</th>
                    <th>Длинна вызова</th>
                    <th>Стоимость звонка</th>
                    <th>Запись разговора</th>
                </tr>
            </thead>
            <tbody>

                {% for cdr in cdrs %}

                <tr class="gradeX">
                    <td><i class="fa fa-clock-o"></i> {{ cdr.callDate }}</td>
                    <td>{{ cdr.a_num }}</td>
                    <td>{{ cdr.b_num }}</td>
                    <td>{{ cdr.billSecSell }} сек.</td>
                    <td>{{ cdr.sellPrice|floatformat:2 }} <i class="fa fa-rub"></i></td>
                    <td>
                        <audio src="/static/1/1.mp3" type="audio/mp3" controls="controls" preload="none"> 
                        </audio>
                    </td> 
                </tr>

                {% endfor %}

            </tbody>

            <tfoot>
                <tr>
                    <th>Дата</th>
                    <th>А-номер</th>
                    <th>Б-номер</th>
                    <th>Длинна вызова</th>
                    <th>Стоимость звонка</th>
                    <th>Запись разговора</th>
                </tr>
            </tfoot>                    
        </table>

    </div>
</div>
                </div>
            </div>

{% endblock %}
{% block scripts %}
<!-- Data Tables -->
<script src="{% static 'js/plugins/dataTables/jquery.dataTables.js' %}"></script>
<script src="{% static 'js/plugins/dataTables/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'js/plugins/dataTables/dataTables.responsive.js' %}"></script>
<script src="{% static 'js/plugins/dataTables/dataTables.tableTools.min.js' %}"></script>
<script src="{% static 'js/plugins/mediaPlayer/mediaelement-and-player.min.js' %}"></script>
<script>
$(document).ready(function() {


  $('audio,video').mediaelementplayer();

  $('.dataTables-example').dataTable({
      responsive: true,
      "lengthMenu": [[50, 100, -1], [50, 100, "All"]],
      "dom": 'T<"clear">lfrtip',
      "tableTools": {
                    "sSwfPath": "{% static 'js/plugins/dataTables/swf/copy_csv_xls_pdf.swf' %}",
                    "aButtons": [
                        "copy",
                        "csv",
                        "xls",
                        "print",
                    ]
                }
  });

});
</script>
{% endblock %}

lk/templates/companies.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    
{% endblock %}

{% block content %}

<div class="ibox">
                        <div class="ibox-title">
                            <h5>Список компаний доступных для просмотра</h5>
                            <div class="ibox-tools">
                                <a href="" class="btn btn-primary btn-xs">Добавить новую компанию</a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <div class="row m-b-sm m-t-sm">
                                <div class="col-md-1">
                                    <button type="button" id="loading-example-btn" class="btn btn-white btn-sm" ><i class="fa fa-refresh"></i> Обновить</button>
                                </div>
                                <div class="col-md-11">
                                    <div class="input-group"><input type="text" placeholder="Search" class="input-sm form-control"> <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Найти!</button> </span></div>
                                </div>
                            </div>

                            <div class="project-list">

                                <table class="table table-hover">
                                    <tbody>
                                    
                                    {% for company in companies %}

                                    <tr>
                                        <td>
                                            <span class="label label-primary">
                                                {% if company.status %}
                                                    {{ company.status }}
                                                {% else %}
                                                    неизвестно
                                                {% endif %}
                                            </span>
                                        </td>
                                        <td>
                                            <a href="{% url 'lk.views.company' company.organizationId %}">{{ company.shortName }}</a>
                                            <br/>
                                            {% if company.vat %}
                                                <small>ИНН: {{ company.vat }}</small>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if company.address1 or company.address2 %}
                                                Адрес: {{ company.address1 }} {{ company.address2 }}<br />
                                            {% endif %}
                                            {% if company.phone1 or company.phone2 %}
                                                Телефон: {{ company.phone1 }} {{ company.phone2 }}
                                            {% endif %}
                                        </td>
                                        <td class="project-people">
                                            <a href=""><img alt="image" class="img-circle" src="{% static 'img/a3.jpg' %}"></a>
                                        </td>
                                        <td class="project-actions">
                                            <a href="{% url 'lk.views.company' company.organizationId %}" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> Открыть </a>
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Редактировать </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

{% endblock %}
{% block scripts %}

{% endblock %}

lk/templates/company.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-lg-9">
		<div class="wrapper wrapper-content animated fadeInUp">
			<div class="ibox">
				<div class="ibox-content">
					<div class="row">
						<div class="col-lg-12">
							<div class="m-b-md">
								<a href="#" class="btn btn-white btn-xs pull-right">Редактировать компанию</a>
								<h2>{{ company.shortname }}</h2>
							</div>
							<dl class="dl-horizontal">
								<dt>Status:</dt> <dd><span class="label label-primary">Active</span></dd>
							</dl>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-5">
							<dl class="dl-horizontal">

								<dt>Полное название:</dt> <dd>{{ company.fullName }}</dd>
								<dt>Город:</dt> <dd>{{ company.cityId.cityName }}</dd>
								<dt>Адрес:</dt> <dd>  {% if company.address1 %}{{ company.address1 }}{% endif %}</dd>
								{% if company.address2 %}
								<dt> </dt> <dd>{{ company.address2 }}</dd>
								{% endif %}

								<dt>Телефон:</dt> <dd>  {% if company.phone1 %}{{ company.phone1 }}{% endif %}</dd>
								{% if company.phone2 %}
								<dt> </dt> <dd>{{ company.phone2 }}</dd>
								{% endif %}
							</dl>
						</div>
						<div class="col-lg-7" id="cluster_info">
							<dl class="dl-horizontal" >

								<dt>ИНН:</dt> <dd>{{ company.vat }}</dd>
								<dt>КПП:</dt> <dd>{{ company.kpp }}</dd>
								<dt>Банк:</dt> <dd>{{ company.bankAccountIdForInvoice.bankId.bankName }}</dd>
								<dt>к.с.:</dt> <dd>{{ company.bankAccountIdForInvoice.bankAccountNumber }}</dd>
								<dt>р.с.:</dt> <dd>{{ company.bankAccountIdForInvoice.bankId.bankCorrAcc }}</dd>
								<dt>БИК:</dt> <dd>{{ company.bankAccountIdForInvoice.bankId.bankBic }}</dd>

								<dt>Контакты:</dt>
								<dd class="project-people">
									<a href=""><img alt="image" class="img-circle" src="{% static 'img/a3.jpg' %}"></a>
									<a href=""><img alt="image" class="img-circle" src="{% static 'img/a1.jpg' %}"></a>
									<a href=""><img alt="image" class="img-circle" src="{% static 'img/a2.jpg' %}"></a>
									<a href=""><img alt="image" class="img-circle" src="{% static 'img/a4.jpg' %}"></a>
									<a href=""><img alt="image" class="img-circle" src="{% static 'img/a5.jpg' %}"></a>
								</dd>
							</dl>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<dl class="dl-horizontal">
								<dt>Кредитный лимит:</dt>
								<dd>
									<div class="progress progress-striped active m-b-sm">
										<div style="width: 60%;" class="progress-bar"></div>
									</div>
									<small>Подсказка</small>
								</dd>
							</dl>
						</div>
					</div>
					<div class="row m-t-sm">
						<div class="col-lg-12">
							<div class="panel blank-panel">
								<div class="panel-heading">
									<div class="panel-options">
										<ul class="nav nav-tabs">
											<li class="active"><a href="#tab-1" data-toggle="tab">Исходящие направления</a></li>
											<li class=""><a href="#tab-2" data-toggle="tab">Входящие направления</a></li>
										</ul>
									</div>
								</div>

								<div class="panel-body">

									<div class="tab-content">
										<div class="tab-pane active" id="tab-1">

											<table class="table table-striped table-bordered table-hover dataTables-example" >
								            <thead>
								                <tr>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                    <th></th>
								                </tr>
								            </thead>
								            <tbody>
								            	{% for tariff in tariffs %}
								            		<tr>
								            			<td>{{ tariff.countryName }}</td>
								            			<td>{{ tariff.name }}</td>
								            			<td>{{ tariff.countryITU }}</td>
								            			<td>{{ tariff.prefix }}</td>
								            			<td>{{ tariff.numberFrom }}</td>
								            			<td>{{ tariff.numberTill }}</td>
								            			<td>{{ tariff.price }}</td>
								            			<td>{{ tariff.dateFrom }}</td>
								            		</tr>
								            	{% endfor %}
								            </tbody>
								           </table>

										</div>

										<div class="tab-pane" id="tab-2">


										</div>
									</div>

								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="wrapper wrapper-content project-manager">
			<h4>Описание компании</h4>
			<img src="{% static 'img/logos/miatelLogo.png' %}" class="img-responsive">
			<p class="small">
				There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look
				even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing
			</p>
			<p class="small font-bold">
				<span><i class="fa fa-circle text-warning"></i> High priority</span>
			</p>
			<h5>Project tag</h5>
			<ul class="tag-list" style="padding: 0">
				<li><a href=""><i class="fa fa-tag"></i> Zender</a></li>
				<li><a href=""><i class="fa fa-tag"></i> Lorem ipsum</a></li>
				<li><a href=""><i class="fa fa-tag"></i> Passages</a></li>
				<li><a href=""><i class="fa fa-tag"></i> Variations</a></li>
			</ul>
			<h5>Project files</h5>
			<ul class="list-unstyled project-files">
				<li><a href=""><i class="fa fa-file"></i> Project_document.docx</a></li>
				<li><a href=""><i class="fa fa-file-picture-o"></i> Logo_zender_company.jpg</a></li>
				<li><a href=""><i class="fa fa-stack-exchange"></i> Email_from_Alex.mln</a></li>
				<li><a href=""><i class="fa fa-file"></i> Contract_20_11_2014.docx</a></li>
			</ul>
			<div class="text-center m-t-md">
				<a href="#" class="btn btn-xs btn-primary">Add files</a>
				<a href="#" class="btn btn-xs btn-primary">Report contact</a>

			</div>
		</div>
		<div>
			<h4>Документы</h4>
			<hr />
			<a href="{% url 'lk:price' company.organizationId %}"><i class="fa fa-file"></i> Текущее тарифное уведомление</a>
			
		</div>
	</div>
</div>


{% endblock %}
{% block scripts %}

<script>
$(document).ready(function() {

	$('.dataTables-example').dataTable({
		responsive: true,
		"lengthMenu": [[50, 100, -1], [50, 100, "All"]],
		"dom": 'T<"clear">lfrtip',
		"tableTools": {
			"sSwfPath": "{% static 'js/plugins/dataTables/swf/copy_csv_xls_pdf.swf' %}",
			"aButtons": [
			"copy",
			"csv",
			"xls",
			"print",
			]
		}
	});

});
</script>
{% endblock %}

lk/templates/nav.html
{% load staticfiles %}

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="{% static 'img/profile_small.jpg' %}" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">David Williams</strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="profile.html">Profile</a></li>
                                <li><a href="contacts.html">Contacts</a></li>
                                <li><a href="mailbox.html">Mailbox</a></li>
                                <li class="divider"></li>
                                <li><a href="login.html">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            TZ
                        </div>
                    </li>
                    <li {% if page == "dashboard" %} class="active" {% endif %}>
                        <a href="{% url 'lk:dashboard' '1' %}"><i class="fa fa-dashboard"></i> <span class="nav-label">Панель управления</span> </a>
                    </li>
                    <li {% if page == "companies" %} class="active" {% endif %}>
                        <a href="{% url 'lk:companies' %}"><i class="fa fa-suitcase"></i> <span class="nav-label">Организации</span> </a>
                    </li>
                    <li {% if page == "cdr" %} class="active" {% endif %}>
                        <a href="{% url 'lk:cdr' '1' %}"><i class="fa fa-list"></i> <span class="nav-label">Детализация</span> </a>
                    </li>
                    <li {% if page == "directions" %} class="active" {% endif %}>
                        <a href="{% url 'lk:directions' %}"><i class="fa fa-exchange"></i> <span class="nav-label">Направления</span> </a>
                    </li>
                    <li {% if page == "banks" %} class="active" {% endif %}>
                        <a href=""><i class="fa fa-bank"></i> <span class="nav-label">Банки</span> </a>
                    </li>
                    <li {% if page == "instruction" %} class="active" {% endif %}>
                        <a href="#"><i class="fa fa-file-text-o"></i> <span class="nav-label">Инструкции</span> </a>
                    </li>
                    
                </ul>

            </div>
        </nav>

lk/templates/sample.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    
{% endblock %}


{% block content %}


{% endblock %}

{% block scripts %}
{% endblock %}